packages:
  - api
  - docs
  - studio
  - frontend
  - 'lib/mod/*'
allowBuilds:
  '@parcel/watcher': true
  canvas: true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@react-pdf-levelup/server@1.1.2'
