packages:
  - api
  - docs
  - studio
  - frontend
  - 'lib'
  - 'lib/mod/*'
allowBuilds:
  '@parcel/watcher': true
  canvas: true
  esbuild: true
  sharp: true

overrides:
  react: 19.2.8
  react-dom: 19.2.8
